[package]
name = "igc"
version = "0.1.0"
authors = ["Tobias Bieniek <tobias.bieniek@gmail.com>"]

[dependencies]
encoding = "0.2.33"
failure = "0.1.3"
lazy_static = "1.2.0"
regex = "1.0.6"

[dev-dependencies]
approx = "^0.3.0"
galvanic-assert = "0.8.7"
proptest = "0.8.7"
