[package]
name = "igc"
version = "0.1.0"
authors = ["Tobias Bieniek <tobias.bieniek@gmail.com>"]

[dependencies]
encoding = "0.2.33"
failure = "0.1.3"
lazy_static = "1.2.0"
regex = "1.0.6"
strum = "0.15.0"
strum_macros = "0.14.0"

[dev-dependencies]
approx = "^0.3.0"
proptest = "0.9.1"
